/map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ''
    topic_name: map
    frame_id: map

/robot_1/amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: robot_1/base_footprint
    odom_frame_id: robot_1/odom
    global_frame_id: map
    scan_topic: scan
    robot_model_type: nav2_amcl::DifferentialMotionModel
    laser_model_type: likelihood_field
    laser_min_range: 0.05
    laser_max_range: 12.0
    laser_likelihood_max_dist: 2.0
    max_beams: 60
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.10
    update_min_a: 0.10
    resample_interval: 1
    transform_tolerance: 0.5
    tf_broadcast: true
    set_initial_pose: true
    always_reset_initial_pose: false
    initial_pose:
      x: 2.3
      y: -14.5
      z: 0.0
      yaw: 1.57079632679
